package natsclient

// Config holds the parameters needed to establish a NATS connection.
type Config struct {
	// ServerURL is the NATS server address, e.g. "nats://localhost:4222".
	ServerURL string

	// CredsFile is the path to a .creds file generated by `nsc generate creds`.
	// Leave empty when running without authentication.
	CredsFile string

	// ConnName labels this connection in the NATS server monitoring dashboard.
	ConnName string
}
